import { Schema } from 'mongoose';
import { PaymentStatus } from '../libs/enums/payment.enum';

const PaymentSchema = new Schema(
  {
    orderId: {
      type: Schema.Types.ObjectId,
      required: true,
      ref: 'Order',
    },

    memberId: {
      type: Schema.Types.ObjectId,
      required: true,
      ref: 'Member',
    },

    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    currency: {
      type: String,
      default: 'KRW', // or USD, EUR
      trim: true,
    },

    status: {
      type: String,
      enum: Object.values(PaymentStatus),
      default: PaymentStatus.PENDING,
    },

    paymentMethod: {
      type: String,
      trim: true, // e.g., 'Card', 'KakaoPay', 'PayPal'
    },

    transactionId: {
      type: String,
      trim: true,
      unique: true, // optional, if generated by gateway
      sparse: true,
    },

    paidAt: { type: Date },
    refundedAt: { type: Date },
    failedAt: { type: Date },
    cancelledAt: { type: Date },

    notes: { type: String, trim: true },

    // Soft delete
    isDeleted: { type: Boolean, default: false },
  },
  { timestamps: true, collection: 'payments' },
);

// 🔥 Indexes
PaymentSchema.index({ orderId: 1 });
PaymentSchema.index({ memberId: 1 });
PaymentSchema.index({ status: 1, updatedAt: -1 });
PaymentSchema.index({ transactionId: 1 });

export default PaymentSchema;
