import { registerEnumType } from '@nestjs/graphql';

/**
 * ERROR CODES (NOT MESSAGES)
 */
export enum ErrorCode {
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  NO_DATA_FOUND = 'NO_DATA_FOUND',
  CREATE_FAILED = 'CREATE_FAILED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  REMOVE_FAILED = 'REMOVE_FAILED',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  BAD_REQUEST = 'BAD_REQUEST',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_BLOCKED = 'USER_BLOCKED',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
  TOKEN_MISSING = 'TOKEN_MISSING',
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  INVALID_ORDER_STATUS_TRANSITION = 'INVALID_ORDER_STATUS_TRANSITION',
  INVALID_DELIVERY_STATUS_TRANSITION = 'INVALID_DELIVERY_STATUS_TRANSITION',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
}
registerEnumType(ErrorCode, {
  name: 'ErrorCode',
});

/**
 * SORT DIRECTION
 */
export enum Direction {
  ASC = 'ASC',
  DESC = 'DESC',
}
registerEnumType(Direction, {
  name: 'Direction',
});